### ISSUE TITLE
'http:' missing in 'app.js'

### ISSUE THREAD

**Issue by rubendibattista** [requirejs/example-jquery-cdn#6]
Hello, 
I'm trying this example on Mac OSX w/ Firefox and it seems that in https://github.com/requirejs/example-jquery-cdn/blob/45052705cdc49d8409dd4bdbda0e5898d986e290/www/js/app.js#L9 `http:` is missing in jquery path set up. 

Is it possible?

**Comment by jrburke** [comment]
That URL style is done on purpose to allow either http: or https:, whatever matches the current document. It is a legitimate URL structure, used for that purpose.

Closing as a discussion ticket, but feel free to continue discussion here.
